
trigger:
  branches:
    include:
      - main #merge trigger

pr:
  branches:
    include:
      - main #pr trigger

pool:
  vmImage: ubuntu-latest


steps:
  - script: |
      sudo apt-get update
      sudo apt-get install -y make golang-go
    displayName: 'Install make and Go'

  - checkout: self #copy the repo in ubuntu

  - script: |
      make integrationcheck
    displayName: 'Run integrationcheck'
