on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'  

      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Run integrationcheck
        run: make integrationcheck"
